### ISSUE TITLE
Missing python-setuptools-rust and setuptools-scm

### ISSUE THREAD

**Issue by Odilhao** [wolfi-dev/os#14]
It's intended to not have setuptools-rust and scm for python packaging/building?

Some libs/modules are not fully compatible with PEP-517 yet 😓

**Comment by kaniini** [comment]
Our intention is to provide py3-setuptools-rust and related packages, but we haven’t bootstrapped rust yet.  It will happen in the next couple of weeks.  Since you’ve requested it explicitly, I will make sure it gets prioritized!On Sep 23, 2022, at 7:01 PM, Odilon Junior ***@***.***> wrote:﻿
It's intended to not have setuptools-rust and scm for python packaging/building?
Some libs/modules are not compatible with PEP-517.
