### ISSUE TITLE
`pip`/`pip3` broken after installation in `wolfi-base` images

### ISSUE THREAD

**Issue by OrBin** [wolfi-dev/os#14880]
Using `wolfi-base` as a base image, I started to get `/bin/sh: pip3: not found` when trying to use pip after installing python and pip.

See example dockerfile (trying to build it reproduces the error):
```dockerfile
FROM cgr.dev/chainguard/wolfi-base:latest

ARG VERSION=3.12

RUN apk update && apk upgrade && apk --no-cache add \
    "python-${VERSION}" \
    "py${VERSION}-pip" \
    && rm -rf /var/cache/apk/*

COPY requirements.txt .
RUN pip3 install -r requirements.txt --no-cache-dir
```

I found out that `pip` and `pip3` actually exist (`/usr/bin/pip`), but their first line is `#!/usr/bin/python`, and the issue is caused by `/usr/bin/python` missing. `/usr/bin/python3` also doesn't exist, only `/usr/bin/python3.12` does.

Also, I see recent changes from yesterday (March 12th) in the definition of python-3.12 package: https://github.com/wolfi-dev/os/commits/main/python-3.12.yaml

**Comment by xnox** [comment]
@smoser right - either we need to revert to previous state; or like flip things that python-3.12 just ships the default python & python3 symlinks, and depends on python-3.12-stdlib or some such; and kill the -default package. Moving default links in retrospect was not as a great idea, as instead of splitting out core things to -stdlib.

**Comment by smoser** [comment]
Hopefully https://github.com/wolfi-dev/os/issues/14880 will fix  for now.

**Comment by OrBin** [comment]
Working on my end too, thanks.
