### ISSUE TITLE
[Wolfi Package Request]: falcosecurity/falco

### ISSUE THREAD

**Issue by Dentrax** [wolfi-dev/os#4342]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://github.com/falcosecurity/falco

### which versions of the software should we include?

latest

### Add some justification for why this specific package and versions are important.

```
grype falcosecurity/falco:latest
 ✔ Vulnerability DB                [updated]
 ✔ Parsed image                                                                                       sha256:928ed230b0b66cbc1cb79191438b71ab89cf7823609744f29afeb6c4ebe1af80
 ✔ Cataloged packages              [287 packages]
 ✔ Scanned for vulnerabilities     [753 vulnerabilities]
   ├── 0 critical, 110 high, 99 medium, 46 low, 488 negligible (10 unknown)
   └── 43 fixed
```

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by tuananh** [comment]
src is here: https://github.com/falcosecurity/falco/blob/master/docker/falco/Dockerfile

sth to note: they download a bunch of deps from `download.falco.org`.

**Comment by LucaGuerra** [comment]
Hi folks, Falco maintainer here :) Thank you <3 

We have exciting developments on this topic. We have been exploring our options and the Falco project is going to experiment with Wolfi based images as we already have two PRs and ongoing discussions about that.

Long story short, Falco has two main images that are used
1. the driver loader image, which contains many compilers including old versions which make scanners go wild (that 100s of "vulns" shown above). It is used to download, compile and run the kernel module or classic eBPF probe
2. the no-driver image which is used to just run Falco once the module is loaded _or_ run the entire thing with the modern eBPF probe (where supported)

We're planning to (1) update the first image while retaining the old one for legacy compatibility (See: https://github.com/falcosecurity/falco/issues/2489 and https://github.com/falcosecurity/falco/pull/2718), making many vulnerabilities vanish and (2) distribute an experimental version of the no-driver which is based on Wolfi instead of Debian slim making pretty much all vulnerabilities vanish (see https://github.com/falcosecurity/falco/pull/2768 and the actual work in https://github.com/falcosecurity/falco/pull/2510 made by @amouat <3 )

Stay tuned for updates on the above as works for the next release of Falco are underway!
