### ISSUE TITLE
Wolfi APK Format add missing Fields for Repology

### ISSUE THREAD

**Issue by henrysachs** [wolfi-dev/os#4363]
Hi there, 

I wanted to use fixed versions in my apko files for installing pinned versions of my packages. But as I'm Lazy I don't want to look up all packages individually and want to use something like Renovate to update all of these automatically. Renovate doesn't offer a so called manager for each package manager itself but adds [repology](https://github.com/repology) as an manager. You can read more about the repology updater for renovate and an example [here](https://docs.renovatebot.com/modules/datasource/repology/)

So I went to ask Repology to add your APK Repositories as an additional source: https://github.com/repology/repology-updater/issues/1339

but unfornately there seem to be some missing fields in the packages itself. I'm not that deep into APK Packaging so I went here to ask if it would be possible to add these?

**Comment by nikaro** [comment]
Can this be re-opened and considered? I'm also interested in using pinned version updated by Renovate.
If you provide me some guidance at where to look and what to do i can maybe put some work on it also.

**Comment by MindTooth** [comment]
> Can this be re-opened and considered? I'm also interested in using pinned version updated by Renovate. If you provide me some guidance at where to look and what to do i can maybe put some work on it also.
> 
> (poke @kaniini )

I came here too to see if Renovate was supported.  It's very relevant since Wolfi provides older versions of many packages.

Who can we contact to solve or get at least an official comment. 🤔

**Comment by henrysachs** [comment]
I think you need to take a look into the repology issue. The Maintainer of Repology showed that wolfi is missing some Identitfiers or fields and wolfi wont add them just for the sake of adding them IIRC. I can totally understand this but haven't found a solution for this. Maybe a RegexManager with a lookup to GitHub Releases (as wolfi versions relate to them most of the time) could atleast be a half solution

**Comment by MPritsch** [comment]
We have this issue as well.

Our workaround is to write a simple service to be able to fetch versions by package name using the wolfi-apk-index:
https://github.com/hown3d/renovate-apk-indexer

Here is an example on how to use it with renovate and gitlab: https://github.com/hown3d/renovate-apk-indexer?tab=readme-ov-file#renovate-gitlab-example

By doing this I learned that the dependency-names of wolfi are inconsistent and hard to automatically read out. I'm not sure if adding the missing fields would address this issue, since they store different versions of the same tool in different dependency names.

Also greeting @henrysachs, hope you are doing well at the DB
