### ISSUE TITLE
Packages provide same file can make installation without version priority

### ISSUE THREAD

**Issue by mesaglio** [wolfi-dev/os#5959]
Hi there! I found in order with the [glibc cve fix](https://www.chainguard.dev/unchained/chainguards-response-to-cve-2023-4527-in-glibc) busybox package need to be rebuild.

The latest version of [busybox](https://github.com/wolfi-dev/os/blob/main/busybox.yaml) `V:1.36.1-r2` have the runtime depdendency with `so:libcrypt.so.1`, but the last version of [glibc](https://github.com/wolfi-dev/os/blob/main/glibc.yaml) `V:2.38-r2` only provides the follow so
```
cmd:ldconfig=2.38-r1
so:libBrokenLocale.so.1=1
so:libanl.so.1=1
so:libc.so.6=6
so:libc_malloc_debug.so.0=0
so:libdl.so.2=2
so:libm.so.6=6
so:libmemusage.so=0
so:libmvec.so.1=1
so:libnsl.so.1=1
so:libnss_compat.so.2=2
so:libnss_dns.so.2=2
so:libnss_files.so.2=2
so:libpthread.so.0=0
so:libresolv.so.2=2
so:librt.so.1=1
so:libthread_db.so.1=1
so:libutil.so.1=1
```
So all images that use `busybox` they remain vulnerable to cve-2023-4527.

To test this we can run the follow commands
```bash
> docker run --rm -it cgr.dev/chainguard/wolfi-base:latest
> $ apk update && apk add --initdb --keys-dir /etc/apk/keys \
  --repositories-file /etc/apk/repositories --root /work busybox
> $ apk list -I | grep glibc
glibc-2.38-r1 x86_64 {glibc} (GPL-3.0-or-later) [installed]
glibc-locale-posix-2.38-r1 x86_64 {glibc} (GPL-3.0-or-later) [installed]
ld-linux-2.38-r1 x86_64 {glibc} (GPL-3.0-or-later) [installed]
libcrypt1-2.38-r1 x86_64 {glibc} (GPL-3.0-or-later) [installed]
```

Is this correctly?

cc @lpcalisi

**Comment by mesaglio** [comment]
@imjasonh

**Comment by jonjohnsonjr** [comment]
Running this myself, I see:

```
apk list -I | grep glibc
glibc-2.38-r2 aarch64 {glibc} (GPL-3.0-or-later) [installed]
glibc-locale-posix-2.38-r2 aarch64 {glibc} (GPL-3.0-or-later) [installed]
ld-linux-2.38-r2 aarch64 {glibc} (GPL-3.0-or-later) [installed]
libcrypt1-2.38-r2 aarch64 {glibc} (GPL-3.0-or-later) [installed]
```

Are you sure you aren't running an older version of the image? You might need to re-pull.

**Comment by mesaglio** [comment]
Sorry my fault, the correct command is 
```bash
apk list --root /work -I | grep glibc
```
we are doing a clean instalation in `/work` directory.

Another thing, we test this in arch and x86 with different results.
---
**aarch64**
```bash
14a4ac1c26ec:/ uname -m
aarch64
14a4ac1c26ec:/ apk update && apk add --initdb --keys-dir /etc/apk/keys \
  --repositories-file /etc/apk/repositories --root /work busybox
fetch https://packages.wolfi.dev/os/aarch64/APKINDEX.tar.gz
 [https://packages.wolfi.dev/os]
OK: 19071 distinct packages available
fetch https://packages.wolfi.dev/os/aarch64/APKINDEX.tar.gz
(1/7) Installing ca-certificates-bundle (20230506-r0)
(2/7) Installing wolfi-baselayout (20230201-r6)
(3/7) Installing ld-linux (2.38-r2)
(4/7) Installing glibc-locale-posix (2.38-r2)
(5/7) Installing glibc (2.38-r2)
(6/7) Installing libcrypt1 (2.38-r2)
(7/7) Installing busybox (1.36.1-r2)
Executing glibc-2.38-r2.trigger
Executing busybox-1.36.1-r2.trigger
OK: 6 MiB in 7 packages
```

**x86_64**
```bash
4170b7208c4d:/ uname -m
x86_64
4170b7208c4d:/ apk update && apk add --initdb --keys-dir /etc/apk/keys  \
  --repositories-file /etc/apk/repositories --root /work busybox
fetch https://packages.wolfi.dev/os/x86_64/APKINDEX.tar.gz
 [https://packages.wolfi.dev/os]
OK: 19319 distinct packages available
fetch https://packages.wolfi.dev/os/x86_64/APKINDEX.tar.gz
(1/6) Installing ca-certificates-bundle (20230506-r0)
(2/6) Installing wolfi-baselayout (20230201-r6)
(3/6) Installing ld-linux (2.38-r2)
(4/6) Installing glibc-locale-posix (2.38-r2)
(5/6) Installing glibc (2.38-r0)
(6/6) Installing busybox (1.36.1-r2)
Executing glibc-2.38-r0.trigger
Executing busybox-1.36.1-r2.trigger
OK: 7 MiB in 6 packages
```

In both case we are pulling the latest wolfi image `cgr.dev/chainguard/wolfi-base:latest`.

**Comment by lpcalisi** [comment]
This issue happens with another packages too. I think that it could be confused because when we install many packages the issue is difficult to reproduce, but.. i we isolate installations, look this:

using the last wolfi-base image, i will try to make a clean instalation of `apk-tools` package in `/work` (empty directory) using the `--initdb` and `--root` apk features

````console
93a05f3258ba:/# apk add --no-scripts --initdb --keys-dir /etc/apk/keys --repositories-file /etc/apk/r
epositories --root /work apk-tools
fetch https://packages.wolfi.dev/os/aarch64/APKINDEX.tar.gz
(1/8) Installing ca-certificates-bundle (20230506-r0)
(2/8) Installing wolfi-baselayout (20230201-r6)
(3/8) Installing glibc (2.37-r3)
(4/8) Installing openssl-config (3.1.3-r0)
(5/8) Installing libcrypto3 (3.1.3-r0)
(6/8) Installing libssl3 (3.1.3-r0)
(7/8) Installing zlib (1.3-r0)
(8/8) Installing apk-tools (2.14.0-r0)
OK: 9 MiB in 8 packages
````

As you can see, glibc is `2.37-r3`. I think that it could be for this [change](https://github.com/wolfi-dev/os/commit/9c338b2cafc104e04cb126e986426e030423b858) in glibc packages. If i try to search which package provides `ld-linux-aarch64.so.1` library, found two.

````console
93a05f3258ba:/# apk search ld-linux-aarch64.so.1
glibc-2.37-r3
ld-linux-2.38-r2
`````

**Comment by lpcalisi** [comment]
I think that is the same case for busybox, if you try to install busybox isolated, installs `glibc (2.38-r0)`. 

````console
9d19201a58ce:/# apk search libcrypt.so.1
glibc-2.38-r0
libcrypt1-2.38-r3
libxcrypt-4.4.36-r0
````

**This only happens on X86_64**

**Comment by jonjohnsonjr** [comment]
Looks like on `x86_64`, all versions prior to `2.37-r3` both provide and depend on `so:ld-linux-x86-64.so.2`.

Whereas on `aarch64`, all versions prior to `2.37-r6` both provide and depend on `so:ld-linux-aarch64.so.1`. 

As you pointed out, this seems to be caused by: https://github.com/wolfi-dev/os/commit/9c338b2cafc104e04cb126e986426e030423b858

I also see that `glibc-2.38-r1` and `glibc-2.38-r2` on both `x86_64` and `aarch64` no longer provide `so:libcrypt.so.1=1`, whereas all prior versions do...

That seems intentional per https://github.com/wolfi-dev/os/commit/4858cbcdb77ec71e4158cb74cd5bf58b711c96fb

@kaniini I am sure you have better ideas for dealing with this than I would.

**Comment by kaniini** [comment]
I suspect this is an apk-tools solver bug, will try to dig into it tonight and see what conclusions I can make

**Comment by mesaglio** [comment]
Hi @kaniini is this close?

**Comment by kaniini** [comment]
I need to examine it further but there is no defect in Wolfi here.  One solution may be to prune the old glibc packages.
