### ISSUE TITLE
postgresql-*-client depends on postgresql-*-dev at runtime

### ISSUE THREAD

**Issue by tuananh** [wolfi-dev/os#792]
we need to declare `postgresql-<version>-dev` as runtime dep of `postgresql-<version>-client`

**Comment by imjasonh** [comment]
`postgresql-11-dev` [depends on `postgresql-11-client`](https://github.com/wolfi-dev/os/blob/main/postgresql-11.yaml#L44-L52), so this would be a circular dependency. Is that expected?

Should the dependency go the other way, or are we saying that in order to use either you have to have both available?

**Comment by tuananh** [comment]
Psql need a so from dev package.

I dont quite get how dev pkg depends on client
